export const marsSportProducts = [
  {
    name: 'Спагетти Карбонара',
    description:
      'Классическое итальянское блюдо с беконом, яйцом, сыром и сливочным соусом.',
    image: require('../assets/product_1.jpg'),
    price: 20,
    count: 1,
  },
  {
    name: 'Фетучини Альфредо',
    description: 'Широкие полоски пасты в нежном сливочном соусе с пармезаном.',
    image: require('../assets/product_2.jpg'),
    price: 22,
    count: 1,
  },
  {
    name: 'Пенне Арабиата',
    description: 'Острая паста с соусом из томатов, чеснока и перца чили.',
    image: require('../assets/product_3.jpg'),
    price: 18,
    count: 1,
  },
  {
    name: 'Лазанья Болоньезе',
    description: 'Слоёная паста с мясным соусом и тянущимся сыром.',
    image: require('../assets/product_4.jpg'),
    price: 25,
    count: 1,
  },
  {
    name: 'Тальятелле с Лососем',
    description: 'Паста с кусочками лосося в сливочно-лимонном соусе.',
    image: require('../assets/product_5.jpg'),
    price: 28,
    count: 1,
  },
  {
    name: 'Равиоли с Рикоттой',
    description: 'Нежные равиоли с начинкой из сыра рикотта и шпината.',
    image: require('../assets/product_6.jpg'),
    price: 23,
    count: 1,
  },
  {
    name: 'Каннеллони с Мясом',
    description: 'Фаршированная паста с мясным соусом и сыром.',
    image: require('../assets/product_7.jpg'),
    price: 24,
    count: 1,
  },
  {
    name: 'Паста Примавера',
    description: 'Овощная паста с томатами, цукини, брокколи и сыром.',
    image: require('../assets/product_8.jpg'),
    price: 19,
    count: 1,
  },
  {
    name: 'Спагетти с Фрикадельками',
    description:
      'Классическое сочетание спагетти с томатным соусом и мясными шариками.',
    image: require('../assets/product_9.jpg'),
    price: 22,
    count: 1,
  },
  {
    name: 'Орекьетте с Брокколи',
    description: 'Паста в форме ушек с брокколи и чесночным маслом.',
    image: require('../assets/product_10.jpg'),
    price: 20,
    count: 1,
  },
  {
    name: 'Ригатони с Сыром',
    description: 'Крупные макароны, запечённые с тягучим сыром и сливками.',
    image: require('../assets/product_11.jpg'),
    price: 21,
    count: 1,
  },
  {
    name: 'Паста с Морепродуктами',
    description: 'Ассорти из морепродуктов в белом винном соусе.',
    image: require('../assets/product_12.jpg'),
    price: 30,
    count: 1,
  },
  {
    name: 'Фузилли с Базиликом',
    description: 'Спиральная паста с соусом песто и кедровыми орешками.',
    image: require('../assets/product_13.jpg'),
    price: 20,
    count: 1,
  },
  {
    name: 'Паста с Трюфелем',
    description: 'Нежная паста с кремовым трюфельным соусом.',
    image: require('../assets/product_14.jpg'),
    price: 35,
    count: 1,
  },
  {
    name: 'Лингвини с Мидиями',
    description: 'Тонкая паста с мидиями и белым вином.',
    image: require('../assets/product_15.jpg'),
    price: 28,
    count: 1,
  },
  {
    name: 'Паста Путанеска',
    description: 'Паста с оливками, анчоусами, каперсами и томатным соусом.',
    image: require('../assets/product_16.jpg'),
    price: 19,
    count: 1,
  },
  {
    name: 'Паста Аматричана',
    description: 'Паста с соусом из бекона, томатов и перца чили.',
    image: require('../assets/product_17.jpg'),
    price: 22,
    count: 1,
  },
  {
    name: 'Спагетти с Цукини',
    description: 'Паста с тонкими ломтиками цукини в чесночном соусе.',
    image: require('../assets/product_18.jpg'),
    price: 20,
    count: 1,
  },
  {
    name: 'Фетучини с Грибами',
    description: 'Широкая паста с грибами в сливочном соусе.',
    image: require('../assets/product_19.jpg'),
    price: 22,
    count: 1,
  },
  {
    name: 'Паста с Цыплёнком',
    description: 'Паста с кусочками курицы и сливочно-чесночным соусом.',
    image: require('../assets/product_20.jpg'),
    price: 24,
    count: 1,
  },
];
